### ISSUE TITLE
[session 04] TODO

### ISSUE THREAD

**Issue by kelvindecosta** [acmbpdc/coding-bootcamp#2]
For local repositories
- [x] Configuring git
- [x] Creating a local repository
- [x] Uploading local repository to GitHub

For collaboration
- [x] Forking a repository
- [x] Cloning a repository
- [x] Creating a branch
- [x] Submitting a pull request

**Comment by kelvindecosta** [comment]
1b4fc7 addresses this issue
